city = ["lijiang", "singapore", "london", "new york"]
print(city)
print(sorted(city))
print(city)
print(sorted(city, reverse = True))
print(city)
city.reverse()
print(city)
city.reverse()
print(city)
city.sort()
print(city)
city.sort(reverse = True)
print(city)